[terminal]
shell = { program = "/usr/local/bin/fish", args = ["-l"] }

[general]
import = [
    "~/.config/alacritty/themes/themes/flexoki.toml"
]

[window]
opacity = 0.85

[font]
normal = { family = "RecMonoLinear Nerd Font"}
size = 21

# Fix Ctrl + i
[keyboard]
bindings = [ { key = 'I', mods = 'Control', chars =  "\u001b[105;5u" } ]

# Fix cursor inverting color
[colors]
cursor = { text = "CellBackground", cursor = "CellForeground" }
vi_mode_cursor = { text = "CellBackground", cursor = "CellForeground" }

